import { VehicleCase, ScannerSettings } from './types';
import { normalizePlate } from '../anpr/normaliser';

export const INITIAL_VEHICLES: VehicleCase[] = [
  {
    id: 'veh-1',
    plateNumber: 'ANN7569',
    normalizedPlate: normalizePlate('ANN7569'),
    customerName: 'Ahmad',
    customerReference: 'CUST-001',
    vehicleMake: 'Perodua',
    vehicleModel: 'Bezza',
    vehicleColor: 'White',
    vehicleYear: 2021,
    vehicleType: 'Sedan',
    financeCompany: 'CIMB',
    outstandingAmount: 15000.00,
    caseReference: 'CIMB001',
    status: 'ACTIVE',
    notes: 'Priority repossession case.',
    plateCategory: 'STANDARD',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'BLACK',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'PETROL',
    isElectricVehicle: false,
    createdAt: new Date('2026-01-15T08:00:00Z').toISOString(),
    updatedAt: new Date('2026-01-15T08:00:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-2',
    plateNumber: 'VAB1234',
    normalizedPlate: normalizePlate('VAB1234'),
    customerName: 'Ahmad',
    customerReference: 'CUST-002',
    vehicleMake: 'Perodua',
    vehicleModel: 'Bezza',
    vehicleColor: 'White',
    vehicleYear: 2020,
    vehicleType: 'Sedan',
    financeCompany: 'CIMB',
    outstandingAmount: 15000.00,
    caseReference: 'CIMB002',
    status: 'ACTIVE',
    notes: 'Contact unsuccessful.',
    plateCategory: 'STANDARD',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'BLACK',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'PETROL',
    isElectricVehicle: false,
    createdAt: new Date('2026-02-10T09:30:00Z').toISOString(),
    updatedAt: new Date('2026-02-10T09:30:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-3',
    plateNumber: 'JSD8888',
    normalizedPlate: normalizePlate('JSD8888'),
    customerName: 'Siti',
    customerReference: 'CUST-003',
    vehicleMake: 'Honda',
    vehicleModel: 'City',
    vehicleColor: 'Black',
    vehicleYear: 2022,
    vehicleType: 'Sedan',
    financeCompany: 'Maybank',
    outstandingAmount: 22000.00,
    caseReference: 'MBB001',
    status: 'ACTIVE',
    notes: 'High priority case.',
    plateCategory: 'STANDARD',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'BLACK',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'PETROL',
    isElectricVehicle: false,
    createdAt: new Date('2026-03-01T10:15:00Z').toISOString(),
    updatedAt: new Date('2026-03-01T10:15:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-4',
    plateNumber: 'WXY7788',
    normalizedPlate: normalizePlate('WXY7788'),
    customerName: 'Ravi',
    customerReference: 'CUST-004',
    vehicleMake: 'Toyota',
    vehicleModel: 'Vios',
    vehicleColor: 'Silver',
    vehicleYear: 2019,
    vehicleType: 'Sedan',
    financeCompany: 'Toyota Capital',
    outstandingAmount: 18000.00,
    caseReference: 'TC001',
    status: 'ON_HOLD',
    notes: 'Case temporarily on hold.',
    plateCategory: 'STANDARD',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'BLACK',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'PETROL',
    isElectricVehicle: false,
    createdAt: new Date('2026-03-15T11:00:00Z').toISOString(),
    updatedAt: new Date('2026-03-15T11:00:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-5',
    plateNumber: 'BQH4281',
    normalizedPlate: normalizePlate('BQH4281'),
    customerName: 'Farah',
    customerReference: 'CUST-005',
    vehicleMake: 'Proton',
    vehicleModel: 'X50',
    vehicleColor: 'Red',
    vehicleYear: 2023,
    vehicleType: 'SUV',
    financeCompany: 'Public Bank',
    outstandingAmount: 28500.00,
    caseReference: 'PBB102',
    status: 'ACTIVE',
    notes: 'Verify vehicle colour before action.',
    plateCategory: 'STANDARD',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'BLACK',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'PETROL',
    isElectricVehicle: false,
    createdAt: new Date('2026-04-05T14:20:00Z').toISOString(),
    updatedAt: new Date('2026-04-05T14:20:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-6',
    plateNumber: 'KV1234E',
    normalizedPlate: normalizePlate('KV1234E'),
    customerName: 'Daniel',
    customerReference: 'CUST-006',
    vehicleMake: 'Nissan',
    vehicleModel: 'Almera',
    vehicleColor: 'Grey',
    vehicleYear: 2018,
    vehicleType: 'Sedan',
    financeCompany: 'Hong Leong Bank',
    outstandingAmount: 12450.00,
    caseReference: 'HLB221',
    status: 'CLOSED',
    notes: 'Account settled.',
    plateCategory: 'LANGKAWI',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'BLACK',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'PETROL',
    isElectricVehicle: false,
    createdAt: new Date('2026-01-10T10:00:00Z').toISOString(),
    updatedAt: new Date('2026-01-10T10:00:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-7',
    plateNumber: 'EV1234',
    normalizedPlate: normalizePlate('EV1234'),
    customerName: 'Lim Guan',
    customerReference: 'CUST-007',
    vehicleMake: 'BYD',
    vehicleModel: 'Atto 3',
    vehicleColor: 'Blue',
    vehicleYear: 2024,
    vehicleType: 'SUV',
    financeCompany: 'RHB Bank',
    outstandingAmount: 34000.00,
    caseReference: 'RHB-EV-88',
    status: 'ACTIVE',
    notes: 'Electric Vehicle JPJePlate white background.',
    plateCategory: 'EV_SPECIAL',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'WHITE',
    expectedCharacterColour: 'BLACK',
    vehicleFuelType: 'ELECTRIC',
    isElectricVehicle: true,
    createdAt: new Date('2026-04-10T12:00:00Z').toISOString(),
    updatedAt: new Date('2026-04-10T12:00:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-8',
    plateNumber: 'W1234A',
    normalizedPlate: normalizePlate('W1234A'),
    customerName: 'Chong Wei',
    customerReference: 'CUST-008',
    vehicleMake: 'Honda',
    vehicleModel: 'Civic FE',
    vehicleColor: 'Black',
    vehicleYear: 2023,
    vehicleType: 'Sedan',
    financeCompany: 'AmBank',
    outstandingAmount: 29800.00,
    caseReference: 'AMB-772',
    status: 'ACTIVE',
    notes: 'Letter-Number-Letter series.',
    plateCategory: 'LETTER_NUMBER_SUFFIX',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'BLACK',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'PETROL',
    isElectricVehicle: false,
    createdAt: new Date('2026-04-12T15:30:00Z').toISOString(),
    updatedAt: new Date('2026-04-12T15:30:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-9',
    plateNumber: 'SAB1234',
    normalizedPlate: normalizePlate('SAB1234'),
    customerName: 'Jeffry Kitingan',
    customerReference: 'CUST-009',
    vehicleMake: 'Toyota',
    vehicleModel: 'Hilux',
    vehicleColor: 'White',
    vehicleYear: 2022,
    vehicleType: 'Pickup',
    financeCompany: 'Sabah Credit',
    outstandingAmount: 24500.00,
    caseReference: 'SCC-909',
    status: 'ACTIVE',
    notes: 'Sabah registration series.',
    plateCategory: 'SABAH',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'BLACK',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'DIESEL',
    isElectricVehicle: false,
    createdAt: new Date('2026-04-14T09:10:00Z').toISOString(),
    updatedAt: new Date('2026-04-14T09:10:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-10',
    plateNumber: 'QAA1234',
    normalizedPlate: normalizePlate('QAA1234'),
    customerName: 'Abang Johari',
    customerReference: 'CUST-010',
    vehicleMake: 'Ford',
    vehicleModel: 'Ranger',
    vehicleColor: 'Silver',
    vehicleYear: 2023,
    vehicleType: 'Pickup',
    financeCompany: 'Bank Islam',
    outstandingAmount: 31000.00,
    caseReference: 'BIMB-101',
    status: 'ACTIVE',
    notes: 'Sarawak Kuching registration series.',
    plateCategory: 'SARAWAK',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'BLACK',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'DIESEL',
    isElectricVehicle: false,
    createdAt: new Date('2026-04-16T11:45:00Z').toISOString(),
    updatedAt: new Date('2026-04-16T11:45:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-11',
    plateNumber: '1122DP',
    normalizedPlate: normalizePlate('1122DP'),
    customerName: 'Embassy Officer',
    customerReference: 'CUST-011',
    vehicleMake: 'Mercedes-Benz',
    vehicleModel: 'E200',
    vehicleColor: 'Black',
    vehicleYear: 2021,
    vehicleType: 'Sedan',
    financeCompany: 'Affinity Capital',
    outstandingAmount: 42000.00,
    caseReference: 'DIP-99',
    status: 'ACTIVE',
    notes: 'Diplomatic red plate.',
    plateCategory: 'DIPLOMATIC',
    plateLayout: 'SINGLE_LINE',
    expectedBackground: 'RED',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'PETROL',
    isElectricVehicle: false,
    createdAt: new Date('2026-04-18T14:00:00Z').toISOString(),
    updatedAt: new Date('2026-04-18T14:00:00Z').toISOString(),
    detectionCount: 0,
  },
  {
    id: 'veh-12',
    plateNumber: 'ABC1234',
    normalizedPlate: normalizePlate('ABC1234'),
    customerName: 'Muthu',
    customerReference: 'CUST-012',
    vehicleMake: 'Yamaha',
    vehicleModel: 'Y15ZR',
    vehicleColor: 'Blue',
    vehicleYear: 2022,
    vehicleType: 'Motorcycle',
    financeCompany: 'Aeon Credit',
    outstandingAmount: 6800.00,
    caseReference: 'AEON-M01',
    status: 'ACTIVE',
    notes: 'Motorcycle 2-line square plate.',
    plateCategory: 'MOTORCYCLE',
    plateLayout: 'TWO_LINE',
    expectedBackground: 'BLACK',
    expectedCharacterColour: 'WHITE',
    vehicleFuelType: 'PETROL',
    isElectricVehicle: false,
    createdAt: new Date('2026-04-20T16:20:00Z').toISOString(),
    updatedAt: new Date('2026-04-20T16:20:00Z').toISOString(),
    detectionCount: 0,
  },
];

export const INITIAL_SETTINGS: ScannerSettings = {
  preferredCamera: 'environment',
  preferredResolution: '720p',
  soundEnabled: true,
  vibrationEnabled: true,
  detectorEngine: 'AUTO',
  ocrEngine: 'TESSERACT',
  detectionThreshold: 0.35,
  recognitionThreshold: 0.60,
  characterConfidenceThreshold: 0.55,
  consensusVotes: 3,
  duplicateCooldown: 30,
  maxTracks: 8,
  maxOcrConcurrency: 3,
  candidatePermutationLimit: 10,
  minCropWidth: 40,
  minCropQuality: 0.20,
  lostTrackTimeout: 20,
  scannerMode: 'MULTI_VEHICLE',
  showCenterGuide: false,
  pauseAfterMatch: false,
  enableSpecialSeries: true,
  enableDiplomatic: true,
  showPlateCategory: true,
  showRawOcr: true,
  showCharConfidence: true,
  debugMode: true,
  demoAssistance: false,
};

