import { ScannerSettings } from './types';

export const INITIAL_SETTINGS: ScannerSettings = {
  preferredCamera: 'environment',
  preferredResolution: '720p',
  soundEnabled: true,
  vibrationEnabled: true,
  detectorEngine: 'AUTO',
  roboflowApiKey: 'QhgkpEMcagyM4hkiKOVl',
  ocrEngine: 'TESSERACT',
  detectionThreshold: 0.35,
  recognitionThreshold: 0.60,
  characterConfidenceThreshold: 0.55,
  consensusVotes: 3,
  duplicateCooldown: 30,
  maxTracks: 8,
  maxOcrConcurrency: 3,
  candidatePermutationLimit: 10,
  minCropWidth: 40,
  minCropQuality: 0.20,
  lostTrackTimeout: 20,
  scannerMode: 'MULTI_VEHICLE',
  showCenterGuide: false,
  pauseAfterMatch: false,
  enableSpecialSeries: true,
  enableDiplomatic: true,
  showPlateCategory: true,
  showRawOcr: true,
  showCharConfidence: true,
  debugMode: true,
  demoAssistance: false,
};
