import { ScannerSettings } from './types';

export const INITIAL_SETTINGS: ScannerSettings = {
  preferredCamera: 'environment',
  preferredResolution: '720p',
  soundEnabled: true,
  vibrationEnabled: true,
  detectionThreshold: 0.45,
  recognitionThreshold: 0.65,
  characterConfidenceThreshold: 0.60,
  consensusVotes: 3,
  duplicateCooldown: 30,
  maxTracks: 8,
  maxOcrConcurrency: 3,
  candidatePermutationLimit: 10,
  minCropWidth: 50,
  minCropQuality: 0.20,
  lostTrackTimeout: 15,
  scannerMode: 'MULTI_VEHICLE',
  showCenterGuide: false,
  pauseAfterMatch: false,
  enableSpecialSeries: true,
  enableDiplomatic: true,
  showPlateCategory: true,
  showRawOcr: true,
  showCharConfidence: true,
  debugMode: true,
  demoAssistance: false,
};
