import { PlateCategory, PlateLayout } from '../db/types';

export interface ValidationTestCase {
  id: string;
  groundTruthPlate: string;
  normalizedGroundTruth: string;
  displayPlate: string;
  expectedCategory: PlateCategory;
  layout: PlateLayout;
  backgroundType: 'BLACK' | 'WHITE' | 'RED' | 'GREEN';
  vehicleType: string;
  lighting: 'DAYLIGHT' | 'NIGHT' | 'PARKING' | 'HEADLIGHT_GLARE';
  movement: 'STATIC' | 'MOVING_VEHICLE' | 'MOVING_CAMERA';
  visiblePlatesCount: number;
  expectedMatchStatus: 'EXACT' | 'POSSIBLE' | 'NONE' | 'CLOSED';
}

export const VALIDATION_MANIFEST: ValidationTestCase[] = [
  {
    id: 'tc-01',
    groundTruthPlate: 'A1234',
    normalizedGroundTruth: 'A1234',
    displayPlate: 'A 1234',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-02',
    groundTruthPlate: 'AB1234',
    normalizedGroundTruth: 'AB1234',
    displayPlate: 'AB 1234',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'POSSIBLE',
  },
  {
    id: 'tc-03',
    groundTruthPlate: 'ABC1234',
    normalizedGroundTruth: 'ABC1234',
    displayPlate: 'ABC 1234',
    expectedCategory: 'MOTORCYCLE',
    layout: 'TWO_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Motorcycle',
    lighting: 'DAYLIGHT',
    movement: 'MOVING_VEHICLE',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-04',
    groundTruthPlate: 'W1234A',
    normalizedGroundTruth: 'W1234A',
    displayPlate: 'W 1234 A',
    expectedCategory: 'LETTER_NUMBER_SUFFIX',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-05',
    groundTruthPlate: 'KV1234E',
    normalizedGroundTruth: 'KV1234E',
    displayPlate: 'KV 1234 E',
    expectedCategory: 'LANGKAWI',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'CLOSED',
  },
  {
    id: 'tc-06',
    groundTruthPlate: 'EV1234',
    normalizedGroundTruth: 'EV1234',
    displayPlate: 'EV 1234',
    expectedCategory: 'EV_SPECIAL',
    layout: 'SINGLE_LINE',
    backgroundType: 'WHITE',
    vehicleType: 'Electric SUV',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-07',
    groundTruthPlate: 'PUTRAJAYA1234',
    normalizedGroundTruth: 'PUTRAJAYA1234',
    displayPlate: 'PUTRAJAYA1234',
    expectedCategory: 'PUTRAJAYA',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-08',
    groundTruthPlate: 'SAB1234',
    normalizedGroundTruth: 'SAB1234',
    displayPlate: 'SAB 1234',
    expectedCategory: 'SABAH',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Pickup',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-09',
    groundTruthPlate: 'QAA1234',
    normalizedGroundTruth: 'QAA1234',
    displayPlate: 'QAA 1234',
    expectedCategory: 'SARAWAK',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Pickup',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-10',
    groundTruthPlate: '1122DP',
    normalizedGroundTruth: '1122DP',
    displayPlate: '1122DP',
    expectedCategory: 'DIPLOMATIC',
    layout: 'SINGLE_LINE',
    backgroundType: 'RED',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'EXACT',
  },
  {
    id: 'tc-11',
    groundTruthPlate: 'ABC9999',
    normalizedGroundTruth: 'ABC9999',
    displayPlate: 'ABC 9999',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'NIGHT',
    movement: 'MOVING_CAMERA',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'NONE',
  },
  {
    id: 'tc-12',
    groundTruthPlate: 'WXY77B8',
    normalizedGroundTruth: 'WXY77B8',
    displayPlate: 'WXY 77 B8',
    expectedCategory: 'STANDARD',
    layout: 'SINGLE_LINE',
    backgroundType: 'BLACK',
    vehicleType: 'Sedan',
    lighting: 'DAYLIGHT',
    movement: 'STATIC',
    visiblePlatesCount: 1,
    expectedMatchStatus: 'POSSIBLE', // Matches WXY7788 via B -> 8 confusion
  },
];
